---
# tasks file for reverse-proxy
- name: Copy systemd service file
  ansible.builtin.copy:
    src: files/systemd/docker-compose@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'
  notify: Systemd Daemon Reload

- name: Copy systemd service file
  ansible.builtin.copy:
    src: files/systemd/docker-compose@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'
  notify: Systemd Daemon Reload

- name: Create docker compose Nginx service directory
  ansible.builtin.file:
    path: /etc/docker/compose/nginx
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Copy docker compose template
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: /etc/docker/compose/nginx/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx Service

- name: Copy nginx config file
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/docker/compose/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx Service

- name: Enable nginx service
  ansible.builtin.systemd:
    name: docker-compose@nginx
    state: started
    enabled: yes