---
- hosts: all
  roles:
    - {role: 'common'}

- hosts: controlNode
  roles:
    - {role: 'dns', tags: 'controlNode'}
    - {role: 'docker', tags: 'controlNode'}
    - {role: 'rancher', tags: 'controlNode'}
    - {role: 'jenkins-master', tags: 'controlNode'}
    - {role: 'reverse-proxy', tags: 'controlNode'}

- hosts: clusterNode
  roles:
    - {role: 'docker', tags: 'clusterNode'}
