version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/pki/tls/certs/home.lan.crt:/certs/home.lan.crt
      - /etc/pki/tls/private/home.lan.key:/certs/home.lan.key
    ports:
      - "80:80"
      - "443:443"
