version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
#      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
