---
# handlers file for roles/jenkins-master
- name: Systemd Daemon Reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Jenkins Service
  ansible.builtin.service:
    name: docker-compose@jenkins
    state: restarted