---
# tasks file for common
- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install ntp server
  yum:
    name: ntp
    state: present

- name: Run ntp service
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Install epel-release repo
  yum:
    name: epel-release
    state: latest

- name: Adding UTF-8 locale
  ansible.builtin.copy:
    src: files/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: '0644'

- name: Copy home.lan CA
  ansible.builtin.copy:
    src: ../../files/certs/HomeLanCA.crt
    dest: /etc/pki/ca-trust/source/anchors/HomeLanCA.crt
    owner: root
    group: root
    mode: '0644'
  notify: Update CA trust

- name: Install ca-certificate package
  ansible.builtin.yum:
    name: ca-certificates
    state: present
