---
# tasks file for docker
- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Add docker repository
  yum_repository:
    name: docker-ce
    description: Docker repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

- name: Install Docker Engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Docker service started
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add execute bit to docker-compose
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    state: link

