---
# tasks file for docker
- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Add docker repository
  yum_repository:
    name: docker-ce
    description: Docker repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

- name: Install Docker Engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Docker service started
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

